on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 48 1 * * *
name: Semgrep
jobs:
  call-semgrep:
    uses: armchairlinguist/semgrep-workflow/.github/workflows/semgrep.yml@main
    secrets: inherit
